# Generated by Django 3.0.1 on 2019-12-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quant', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
