# Generated by Django 3.0.1 on 2019-12-22 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quant',
            new_name='quantity',
        ),
    ]
